package MapReduce.Thrift;
import JavaWorker.DataSyncWrapper;
import MapReduce.Thrift.AutoGenerated.ClientListeningInfo;
import MapReduce.Thrift.AutoGenerated.KeyValueEntity;
import MapReduce.Thrift.AutoGenerated.MapReduceWorker;
import PythonPoCClient.PythonRunner;
import org.apache.commons.lang3.Pair;

import java.util.List;
import java.util.Random;


/**
 * Created by msuchock on 27.05.2018.
 */

public class MapReduceWorkerHandler implements MapReduceWorker.Iface {
    private String dataFileName;
    private String mapFileName;
    private String reduceFileName;
    private List<ClientListeningInfo> workersList;
    private PythonRunner pyRunner;
    private DataSyncWrapper dataSyncWrapper;


    public MapReduceWorkerHandler(DataSyncWrapper dataSyncWrapper){
        this.dataSyncWrapper = dataSyncWrapper;
    }

    public boolean AssignWork(String dataFileName, String mapFileName, String reduceFileName, List<ClientListeningInfo> workersList) {
        this.dataFileName = dataFileName;
        this.mapFileName = mapFileName;
        this.reduceFileName = reduceFileName;
        this.workersList = workersList;
        pyRunner = new PythonRunner(dataFileName, mapFileName, reduceFileName);

        System.out.println("Get data: " + this.dataFileName + " map: " + this.mapFileName + " reduce: " + this.reduceFileName);
        System.out.println("Workers:");
        this.workersList.forEach(x -> System.out.println(x.toString()));
        return true;
    }

    public boolean StartMap() {
        System.out.println("Map begins");
        pyRunner.map(dataSyncWrapper);
        try {
            System.in.read();
        } catch (Exception e){
            System.out.println("Exception occured while reading key");
            return false;
        }
        return true;
    }

    public boolean StartReduce() {
        System.out.println("Reduce begins");
        pyRunner.reduce(dataSyncWrapper);
        synchronized (dataSyncWrapper){
            dataSyncWrapper.reduceFinished();
        }
        return true;
    }

    public int Ping()
    {
        return new Random().nextInt();
    }

    public void RegisterMapPair(List<KeyValueEntity> pairs) {
        System.out.println("I got pairs:");
        pairs.forEach(x -> {
            System.out.println(String.valueOf(x.getKey()) + " -> " + String.valueOf(x.getValue()) + " with quantity: " + String.valueOf(x.getQuantity()));
            for(int i=0; i<x.getQuantity(); i++){
                //adding as many pairs as quantity in pair
                dataSyncWrapper.addToMyKeyValuesMap(new Pair<>(x.getKey(),Integer.valueOf(x.getValue())));
            }
        });
    }
}



